apiVersion: v1
kind: Pod
metadata:
  name: var-ejemplo
  labels:
    app: variables 
spec:
  containers:
  - name: contenedor-variables
    image: gcr.io/google-samples/node-hello@sha256:d238d0ab54efb76ec0f7b1da666cefa9b40be59ef34346a761b8adc2dd45459b
    env:
    - name: NOMBRE
      value: "CURSO DE KUBERNETES"
    - name: PROPIETARIO
      value: "Apasoft Training"

